
[functions.translate-business-description]
enabled = true
verify_jwt = true
import_map = "./functions/translate-business-description/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/translate-business-description/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/translate-business-description/*.html" ]

[functions.translate-offering-description]
enabled = true
verify_jwt = true
import_map = "./functions/translate-offering-description/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/translate-offering-description/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/translate-offering-description/*.html" ]

[functions.mp-oauth-start]
enabled = true
verify_jwt = true
import_map = "./functions/mp-oauth-start/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/mp-oauth-start/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/mp-oauth-start/*.html" ]

[functions.mp-oauth-callback]
enabled = true
verify_jwt = true
import_map = "./functions/mp-oauth-callback/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/mp-oauth-callback/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/mp-oauth-callback/*.html" ]

[functions.mp-create-charge]
enabled = true
verify_jwt = true
import_map = "./functions/mp-create-charge/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/mp-create-charge/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/mp-create-charge/*.html" ]

[functions.mp-webhook]
enabled = true
verify_jwt = true
import_map = "./functions/mp-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/mp-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/mp-webhook/*.html" ]
